### ISSUE TITLE
Case-sensitive or not?

### ISSUE THREAD

**Issue by tpluscode** [zazuko/api-testing-dsl#4]
In all my snippets I have been pretty much assuming the syntax to be case-sensitive. For example `Expect Property` is good but `expect property` is not. 

Should we keep it that way? A more relaxed DSL would be better maybe?

**Comment by mchlrch** [comment]
At the moment, the syntax is case-sensitive. We could change that and ignore case for keywords be modifying the configuration in https://github.com/zazuko/api-testing-dsl/blob/master/com.zazuko.apitesting.dsl/com.zazuko.apitesting.dsl/src/com/zazuko/apitesting/dsl/GenerateApiTestingDsl.mwe2

See: 
https://stackoverflow.com/questions/30889847/match-string-in-xtext-regardless-of-upper-lower-case

**Comment by tpluscode** [comment]
Any opinion? I'd personally like to keep it sensitive but 🤷‍♂

**Comment by mchlrch** [comment]
I prefer to keep it case sensitive as well. It's the default and I don't see a disadvantage sticking to the default.

**Comment by tpluscode** [comment]
Ok, keeping the current behaviour then 👍
